#!/bin/sh
# Bootstrap this package from checked-out sources.
base=$(realpath $(dirname "$0"))

# Do not fail
set -euo pipefail
IFS=$'\n\t'

# Ensure file names are sorted consistently across platforms.
export LC_ALL=C

# Ensure that CDPATH is not set.  Otherwise, the output from cd
# would cause trouble in at least one use below.
(unset CDPATH) >/dev/null 2>&1 && unset CDPATH

# Be verbose upon failures
yell() { echo "$0: $*" >&2; }
die() { yell "$*"; exit 1; }
try() { "$@" || die "Failed to execute: $*"; }
run() { echo "Run: $@" && try $@; }

# Work from package's base
cd ${base} > /dev/null

# Let autotools do their magic
builddir=${base}/build
run mkdir -p ${builddir}
run aclocal -I m4
run autoheader
run libtoolize --automake --copy --install -f
run autoconf
run automake --add-missing --copy -Woverride
#autoreconf -i --verbose || exit $?
run autoreconf -i

cd - > /dev/null

