# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
#                           The Funex File-System                             #
#                                                                             #
#  Copyright (C) 2014, 2015 Synarete                                          #
#                                                                             #
#  Funex is a free software: you can redistribute it and/or modify it under   #
#  the terms of the GNU General Public License as published by the Free       #
#  Software Foundation, either version 3 of the License, or (at your option)  #
#  any later version.                                                         #
#                                                                             #
#  Funex is distributed in the hope that it will be useful, but WITHOUT ANY   #
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  #
#  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more      #
#  details.                                                                   #
#                                                                             #
#  You should have received a copy of the GNU General Public License along    #
#  with this program. If not, see <http://www.gnu.org/licenses/>              #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Import helper wrapper
import sconsx

# Environment
funex_env = sconsx.Environment()
Export('funex_env')

# Common search-path
funex_env.AppendIncludePath('include')
funex_env.AppendIncludePath('#')

# Library
funex_env.SubSConscript('libfnx')

# Applications
funex_env.SubSConscript('apps')

# Unitests
funex_env.SubSConscript('unitests')

# Show build info
funex_env.ShowVars()
