# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#                                                                             #
#                           The Funex File-System                             #
#                                                                             #
#  Copyright (C) 2014, 2015 Synarete                                          #
#                                                                             #
#  Funex is a free software: you can redistribute it and/or modify it under   #
#  the terms of the GNU General Public License as published by the Free       #
#  Software Foundation, either version 3 of the License, or (at your option)  #
#  any later version.                                                         #
#                                                                             #
#  Funex is distributed in the hope that it will be useful, but WITHOUT ANY   #
#  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS  #
#  FOR A PARTICULAR PURPOSE. See the GNU General Public License for more      #
#  details.                                                                   #
#                                                                             #
#  You should have received a copy of the GNU General Public License along    #
#  with this program. If not, see <http://www.gnu.org/licenses/>              #
#                                                                             #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

Import('funex_env')

subs = Split('fusei vproc pstor core infra hash')
srcs = Glob('*.c') + [Glob(sub + '/*.c') for sub in subs]
funex_env.StaticLibrary(target='fnx', source=srcs)
funex_env.AppendLibPath('.')
