theme = "meliora"

[editor]
line-number = "absolute"
cursorline = true
rulers = [80]

[editor.lsp]
display-messages = true
auto-signature-help = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "bar"

[editor.whitespace.render]
space = "all"
tab = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
tab = "»"
tabpad = " "

[editor.statusline]
left = ["mode", "spinner", "separator", "file-name", "file-modification-indicator"]
right = ["separator", "version-control", "file-type", "position"]
separator = "¦"
