" vimrc
"

" Disable vi compatibility (crucial for modern features)
set nocompatible

" Enable true colors
set termguicolors

" Enable line numbers by default
set nu
set numberwidth=4

" Add a bit extra margin to the left
set foldcolumn=1

" Show whitespace characters
set list

" Mark white-character visible
"set list listchars=tab:>-,nbsp:.,trail:.,extends:>,precedes:<
set listchars=tab:»\ ,extends:›,precedes:‹,nbsp:·,trail:·
set showbreak=\\\

" Keep 100 lines of command line history
set history=100

" Show the cursor position all the time
set ruler

" Highlight current line
set cursorline

" Set to auto read when a file is changed from the outside
set autoread

" Highlight search results
set hlsearch

" Makes search act like search in modern browsers
set incsearch
set smartcase

" Show matching brackets when text indicator is over them
set showmatch

" Enable syntax highlighting
syntax enable

" Indentation
set autoindent
set smartindent
set smarttab
set shiftround

" Tab settings
set tabstop=8

" Enable filetype plugins
filetype plugin on
filetype indent on

" XTerm Color
set t_Co=256

" Better key-mapping experience
set timeout timeoutlen=1000 ttimeoutlen=10

" C Filetype specific settings
autocmd FileType c setlocal tabstop=8 shiftwidth=8 noexpandtab
autocmd FileType c setlocal cinoptions=:0,l1,t0,g0,(0,M4
autocmd FileType c setlocal cindent
autocmd FileType c setlocal comments=sr:/*,mb:*,ex:*/,://
autocmd FileType c setlocal textwidth=80
autocmd FileType c setlocal formatoptions=tcqlron

" Better C syntax highlighting
let c_space_errors = 1
let c_no_trail_space_error = 0
let c_no_tab_space_error = 0
let c_comment_strings = 1
let c_gnu = 1
let c_syntax_for_h = 1

" Python/Shell Filetype specific settings
autocmd FileType python setlocal tabstop=4 shiftwidth=4 expandtab
autocmd FileType sh,bash setlocal tabstop=8 shiftwidth=4 expandtab
autocmd FileType sh,bash setlocal textwidth=80

" Git commit settings
autocmd FileType gitcommit setlocal textwidth=72
autocmd FileType gitcommit setlocal colorcolumn=50,72
autocmd FileType gitcommit setlocal spell spelllang=en_us
autocmd FileType gitcommit setlocal complete+=kspell
autocmd FileType gitcommit setlocal formatoptions+=tqn
autocmd FileType gitcommit setlocal formatoptions-=l
autocmd FileType gitcommit setlocal comments=:#,fb:-,fb:*

" Git commit start in normal mode a first line
autocmd FileType gitcommit call setpos(".", [0, 1, 1, 0])

" Git rebase-interactive settings
autocmd FileType gitrebase setlocal nofoldenable
autocmd FileType gitrebase setlocal bufhidden=delete

" Git rebase-interactive single-key shortcuts
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> p :s/^\w\+/pick/<CR>:nohlsearch<CR>
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> r :s/^\w\+/reword/<CR>:nohlsearch<CR>
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> e :s/^\w\+/edit/<CR>:nohlsearch<CR>
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> s :s/^\w\+/squash/<CR>:nohlsearch<CR>
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> f :s/^\w\+/fixup/<CR>:nohlsearch<CR>
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> d :s/^\w\+/drop/<CR>:nohlsearch<CR>
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> x :s/^\w\+/exec/<CR>A
autocmd FileType gitrebase nnoremap
    \ <buffer> <silent> b :s/^\w\+/break/<CR>:nohlsearch<CR>

" Color scheme
try
  colorscheme jellybeans
catch 
  colorscheme desert
endtry
set background=dark

" Colored line-numbers
highlight LineNr term=bold cterm=NONE ctermfg=DarkGray ctermbg=NONE
    \ gui=NONE guifg=Gray16 guibg=NONE

" Colored colum at 80
highlight ColorColumn ctermbg=3 guibg=Gray3
set colorcolumn=80
autocmd FileType gitcommit set colorcolumn=72
autocmd FileType rst,markdown set colorcolumn=72,80

" Set utf8 as standard encoding and en_US as the standard language
set encoding=utf8

" Use Unix as the standard file type
set ffs=unix,dos,mac

" Turn backup off
set noswapfile
set nobackup
set nowritebackup

" Perforamce optimazation
set lazyredraw
set ttyfast

" Encypt strongly
set cm=blowfish2
set viminfo=

" Scrolling
set sidescroll=1

" Bettwer Wildmenu
set wildmenu
set wildmode=longest:full,full
set wildignore=*.p,*.obj,*~,*,pyc,*.swp

" Spell-check in git commits
autocmd FileType gitcommit setlocal spell

" Spell-check for text markdown and restructuredtext
autocmd BufRead,BufNewFile *.txt setlocal spell
autocmd BufRead,BufNewFile *.md setlocal spell
autocmd BufRead,BufNewFile *.rst setlocal spell
autocmd BufRead,BufNewFile *.tex setlocal spell

" Avoid noisy cscope
set nocscopeverbose

" Mouse support
set mouse=a

" Use system clipboard
set clipboard=unnamedplus

" Clear search highlight
nnoremap <silent> <Esc><Esc> :nohlsearch<CR>

" Display buffers-list with F5
nnoremap <F5> :buffers<CR>:buffer<Space>
" Cycle buffers
nnoremap <C-n> :bnext<CR>
nnoremap <C-p> :bprevious<CR>

" Status bar colors
au InsertEnter * hi statusline
	\ guifg=black guibg=#d7afff ctermfg=black ctermbg=magenta
au InsertLeave * hi statusline
	\ guifg=black guibg=#8fbfdc ctermfg=black ctermbg=cyan
hi statusline guifg=black guibg=#8fbfdc ctermfg=black ctermbg=cyan

" Status line
" default: set statusline=%f\ %h%w%m%r\ %=%(%l,%c%V\ %=\ %P%)

" Status Line Custom
let g:currentmode={
    \ 'n'  : 'Normal',
    \ 'no' : 'Normal·Operator Pending',
    \ 'v'  : 'Visual',
    \ 'V'  : 'V·Line',
    \ '^V' : 'V·Block',
    \ 's'  : 'Select',
    \ 'S'  : 'S·Line',
    \ '^S' : 'S·Block',
    \ 'i'  : 'Insert',
    \ 'R'  : 'Replace',
    \ 'Rv' : 'V·Replace',
    \ 'c'  : 'Command',
    \ 'cv' : 'Vim Ex',
    \ 'ce' : 'Ex',
    \ 'r'  : 'Prompt',
    \ 'rm' : 'More',
    \ 'r?' : 'Confirm',
    \ '!'  : 'Shell',
    \ 't'  : 'Terminal'
    \}

set laststatus=2
set noshowmode
set statusline=
set statusline+=%0*\ %n\                                 " Buffer number
set statusline+=%1*\ %<%F%m%r%h%w\  " Path, modified, readonly, helpfile, prev
set statusline+=%3*│                                     " Separator
set statusline+=%2*\ %Y\                                 " FileType
set statusline+=%3*│                                     " Separator
set statusline+=%2*\ %{''.(&fenc!=''?&fenc:&enc).''}     " Encoding
set statusline+=\ (%{&ff})                               " FileFormat
set statusline+=%=                                       " Right Side
set statusline+=%2*\ col:\ %02v\                         " Colomn number
set statusline+=%3*│                                     " Separator
set statusline+=%1*\ ln:\ %02l/%L\ (%3p%%)\              " Line-# / Total %
set statusline+=%0*\ %{toupper(g:currentmode[mode()])}\  " The current mode

hi User1 ctermfg=007 ctermbg=239 guibg=#4e4e4e guifg=#adadad
hi User2 ctermfg=007 ctermbg=236 guibg=#303030 guifg=#adadad
hi User3 ctermfg=236 ctermbg=236 guibg=#303030 guifg=#303030
hi User4 ctermfg=239 ctermbg=239 guibg=#4e4e4e guifg=#4e4e4e

" Minimal setup for files browsing
let g:netrw_banner = 0
let g:netrw_liststyle = 3
let g:netrw_browse_split = 4
let g:netrw_altv = 1
let g:netrw_winsize = 25

" Add format option 'w' to add trailing white space, indicating that
" paragraph continues on next line. This is to be used with mutt's
" 'text_flowed' option.
augroup mail_trailing_whitespace " {
    autocmd!
    autocmd FileType mail setlocal formatoptions+=w
augroup END " }
