#
# Ubuntu template Dockerfile for testing Funex builds on debian-based machine
#
# Based on: https://github.com/dockerfile/ubuntu
#

# Pull base image.
FROM ubuntu:15.04

# Install.
RUN \
  apt-get update && \
  apt-get -y upgrade && \
  apt-get install -y build-essential && \
  apt-get install -y software-properties-common && \
  apt-get install -y byobu curl git htop man unzip vim wget

# Extra packages for build
RUN \
  apt-get install -y asciidoc astyle automake autotools-dev \
    bash-completion build-essential clang cloc man-db coreutils \
    devscripts dh-make diffutils dwarves fuse-dbg g++ gcc gdb \
    gettext-base gettext libmount-dev git git-completion git-core \
    git-email git-man git-svn libattr1-dev libcap-dev libfuse-dev \
    libtool libunwind8 libunwind8-dev make moreutils most pkg-config \
    pychecker python-docutils python-optcomplete python-pyudev \
    realpath scons tree uuid-dev libssl-dev libexpat1-dev


# Allow mapping host uid, gid & home
RUN groupadd --gid @GID@ @GROUP@
RUN useradd --uid @UID@ --gid @GID@ --home-dir @HOME@ --create-home @NAME@
VOLUME @HOME@

# Add files.
ADD root/bashrc @HOME@/.bashrc
ADD root/gitconfig @HOME@/.gitconfig
ADD root/scripts @HOME@/.scripts

# Set environment variables.
ENV HOME @HOME@
ENV UID @UID@

# Define working directory.
WORKDIR @HOME@

# Define default command.
CMD ["bash"]
