#!/usr/bin/env python
import sys
from os.path import basename
from setproctitle import setproctitle 
from cstylechecker import checkcstyle 

setproctitle(basename(sys.argv[0]))
rc = checkcstyle(sys.argv[1:])
sys.exit(rc)

