#! /bin/bash

rpm-dump()
{
    if [ $# -ne 1 ] ; then
        printf "\aUSAGE: $FUNCNAME <rpm-path>\n" 1>&2
        return 1
    fi
    if [ ! -e "$1" -o ! -r "$1" -o ! -f "$1" ] ; then
        printf "either '$1' does not exist, or it's not an RPM, or it's not accessible\n" 1>&2
        return 2
    fi
    local path=$(readlink -f "$1")
    if ! file -b "$path" | grep '^RPM' ; then
        printf "'$1' does not appear to be an RPM file.\n"
        return 3
    fi
    rpm2cpio "$path" | cpio -tv
}

for f in "$@"
do
    rpm-dump "$f"
done

