# shellcheck shell=bash
# User specific bash settings

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source system files
source /etc/bashrc
source /etc/profile

# Check the window size after each command and update
shopt -s checkwinsize

# Try-source git system-wide files
_try_source() { if [ -f "$1" ]; then source "$1"; fi }
_try_source /usr/share/git-core/contrib/completion/git-prompt.sh
_try_source /etc/bash_completion.d/git-prompt

# Dotfiles' root-dir
ROOT="$(realpath "$(dirname "${BASH_SOURCE[0]}")"/../)"

# Colors & functions
source "${ROOT}/bash/bash_colors"
source "${ROOT}/bash/bash_functions"

# Prompt (PS1)
source "${ROOT}/bash/bash_prompt"

# Aliases
source "${ROOT}/bash/bash_alias"

# Misc
source "${ROOT}/bash/bash_misc"

# Have python history file
export PYTHONSTARTUP=${ROOT}/bash/pystartup

# Extra tools
export PATH="${HOME}"/.local/bin:"${ROOT}"/bin:${PATH}
