#
# USER SPECIFIC:
#

# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Source system files
sysfiles=(
	/etc/bashrc
	/etc/profile
        /usr/share/git-core/contrib/completion/git-prompt.sh
	 )
for f in "${sysfiles[@]}"; do
	if [ -f "$f" ]; then
		source "$f"
	fi
done

# Dotfiles' root-dir
#ROOT=$(realpath $(dirname $BASH_SOURCE[0])/../)
ROOT=${HOME}/synarete/dotfiles

# Colors & functions
source ${ROOT}/bash/bash_colors
source ${ROOT}/bash/bash_functions

# Bash history
export HISTSIZE=10000
export HISTCONTROL=ignoreboth:erasedups

# Prompt
#export PS1='[\u@\h \W]\$ '
export PROMPT_DIRTRIM=3
export GIT_PS1_SHOWDIRTYSTATE=1
export GIT_PS1_SHOWSTASHSTATE=1
export GIT_PS1_SHOWUNTRACKEDFILES=1
export PS1="[\u@\h ${BRIGHT_VIOLET}\w${NORMAL}${NORMAL}]${BRIGHT_YELLOW}\$(__git_ps1)${NORMAL}\$ ${RESET}"

# Editor
export EDITOR=emacs

# Aliases
alias ll='ls -lh'
alias ltr='ls -ltrh'
alias la='ls -A'
alias l='ls -CF'
alias cd..='cd ..'
alias tree='tree -C -F --dirsfirst'
alias find-ch='find -type f -name "*.[ch]" '
alias emc='emacsclnt'
alias emd-start='emacsd_start'
alias emd-stop='emacsd_stop'

# Check the window size after each command and update
shopt -s checkwinsize

# Be generous to Java apps (eclipse)
export _JAVA_OPTIONS="-Xms512m -Xmx1g"

# Have python history file
export PYTHONSTARTUP=${ROOT}/bash/pystartup
