#!/bin/bash -e
self=$(basename ${BASH_SOURCE[0]})
msg() { echo "$self: $*" >&2; }
die() { msg "$*"; exit 1; }
try() { "$@" || die "Failed to execute: $*"; }
run() { echo "$self: $@" >&2; try "$@"; }

export LC_ALL=C
unset CDPATH

name=cauta
selfdir=$(realpath $(dirname ${BASH_SOURCE[0]}))
basedir=$(realpath ${selfdir}/../)
version_sh=${basedir}/version.sh
version=$(try ${version_sh} --version)
release=$(try ${version_sh} --release)
revision=$(try ${version_sh} --revision)
archive_tgz=${name}-${version}.tar.gz

builddir=${basedir}/build
buildauxdir=${builddir}/rpm
autotoolsdir=${buildauxdir}/autotools/

rpmsourcedir=${selfdir}/rpm
rpmbuilddir=${buildauxdir}/rpmbuild
rpmtmpdir=${rpmbuilddir}/tmp
rpmdate=$(date +"%a %b %d %Y")
rpmspec_in=${rpmsourcedir}/${name}.spec.in
rpmspec_out=${rpmbuilddir}/SPECS/${name}.spec

# Prerequisites checks
run which rpmbuild
run which aclocal
run which automake
run which libtoolize
run which rst2man

# Autotools build
run mkdir -p ${autotoolsdir}
run cd ${autotoolsdir}
run ${basedir}/bootstrap
run ${basedir}/configure
run make
run make check dist distcheck

# Prepare rpm tree
run mkdir -p ${rpmtmpdir}
run mkdir -p ${rpmbuilddir}
run mkdir -p ${rpmbuilddir}/RPMS
run mkdir -p ${rpmbuilddir}/SOURCES
run mkdir -p ${rpmbuilddir}/SPECS
run mkdir -p ${rpmbuilddir}/SRPMS
run mkdir -p ${rpmbuilddir}/BUILDROOT

# Generate spec
run sed \
  -e "s,[@]NAME[@],${name},g" \
  -e "s,[@]VERSION[@],${version},g" \
  -e "s,[@]RELEASE[@],${release},g" \
  -e "s,[@]REVISION[@],${revision},g" \
  -e "s,[@]RPMDATE[@],${rpmdate},g" \
  ${rpmspec_in} > ${rpmspec_out}

# Copy dist archive
run cp ${autotoolsdir}/${archive_tgz} ${rpmbuilddir}/SOURCES

# Execute rpmbuild
run cd ${rpmbuilddir}
run rpmbuild -ba --clean \
  --define "_topdir ${rpmbuilddir}" \
  --define "_tmppath ${rpmtmpdir}" ${rpmspec_out}

# Copy rpms to root of build-dir
run find ${rpmbuilddir}/RPMS/ ${rpmbuilddir}/SRPMS/ \
  -type f -name ${name}'*.rpm' \
  -exec cp {} ${builddir} \;

# Cleanup build staging area
run cd ${basedir}
run rm -rf ${buildauxdir}

# Bye ;)
run ls ${builddir}/${name}*.rpm



